version: '3.8'
services:
  main-nginx:
    build:
      context: .
    image: main-nginx:latest # 为镜像指定一个名称
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./var/log/nginx:/var/log/nginx
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - main-network
networks:
  main-network:
    external: true

